# SkyCAIR OS — Calamares Installer Settings
# 2XR, LLC | Evolve2Linux | 123Tech.net
---
modules-search: [ local, /usr/lib/calamares/modules ]

instances: []

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - bootloader-config
    - grubcfg
    - bootloader
    - shellprocess@post-install
    - preservefiles
    - umount
  - show:
    - finished

branding: skycair

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: false
quit-at-end: false
