# Calamares bootloader module — SkyCAIR OS (GRUB2)
---
installEFI:         true
efiSystemPartition: "/boot/efi"
efiCanCreatePartitions: false
grubInstall:        "grub-install"
grubMkconfig:       "grub-mkconfig"
grubCfg:            "/boot/grub/grub.cfg"
grubFallback:       false

timeout: 5

kernelLine:    " quiet splash"
kernelLineUndo: ""

entry-name: "SkyCAIR OS EODv9"
