# Calamares partition module — SkyCAIR OS
---
efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: 300
efiSystemPartitionName: "EFI System Partition"

userSwapChoices:
  - none
  - small
  - suspend
  - file

drawNestedPartitions:  false
alwaysShowPartitionLabels: true
initialPartitioningChoice: erase
initialSwapChoice: small

defaultFileSystemType: "ext4"

availableFileSystemTypes:
  - "ext4"
  - "btrfs"
  - "xfs"
