# Calamares users module — SkyCAIR OS
---
defaultGroups:
  - name: users
    must_exist: true
    system: false
  - name: lp
    must_exist: false
    system: true
  - name: video
    must_exist: false
    system: true
  - name: audio
    must_exist: false
    system: true
  - name: wheel
    must_exist: false
    system: true
  - name: plugdev
    must_exist: false
    system: true
  - name: netdev
    must_exist: false
    system: true
  - name: scanner
    must_exist: false
    system: true
  - name: bluetooth
    must_exist: false
    system: true

autologinGroup:  autologin
sudoersGroup:    wheel
setRootPassword: true
doAutologin:     false
passwordRequirements:
  minLength:  8
  maxLength:  -1

userShell: /bin/bash

forbiddenNames:
  - root
  - skycair
  - guest
