# Calamares welcome module — SkyCAIR OS
---
showSupportUrl:      true
showKnownIssuesUrl:  true
showReleaseNotesUrl: true
showDonateUrl:       false

requirements:
  requiredStorage:    20.0
  requiredRam:        2.0
  checkHasInternet:   false
  checkForUpdates:    false
  checkFirmwareType:  false
  checkBatteryLevel:  10
